(function(){'use strict';
var e,g="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},l="object"===typeof g.global&&g.global?g.global:"object"===typeof global&&global&&global.Object===Object?global:this;g.global=l;var aa="object"===typeof g.exportsNamespace&&g.exportsNamespace?g.exportsNamespace:l;g.exportsNamespace=aa;l.Object.freeze(g);var ba={envInfo:g,semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.13"};l.Object.freeze(ba);l.Object.freeze(ba.semantics);
var n=l.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ca=l.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},da=0,ea=l.WeakMap?new l.WeakMap:null;function p(a){return function(b,c){return!(!b||!b.a||b.a.U!==c||b.a.S!==a)}}function fa(a){for(var b in a)return b}
function ga(a,b,c){var d=new a.vb(b[c]);if(c<b.length-1){a=a.W;c+=1;for(var f=d.A,h=0;h<f.length;h++)f[h]=ga(a,b,c)}return d}function ha(a){return void 0===a?"undefined":a.toString()}
function ia(a){switch(typeof a){case "string":return q(ja);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?q(ka):b<<16>>16===b&&1/b!==1/-0?q(la):q(ma):"number"===typeof a?q(na):q(oa);case "boolean":return q(pa);case "undefined":return q(qa);default:return null===a?a.Vc():ra(a)?q(sa):a&&a.a?q(a.a):null}}
function ta(a){switch(typeof a){case "string":return ua(t(),a);case "number":return va(wa(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.a||null===a?a.j():null===ea?42:xa(a)}}function ya(a,b){var c=l.Object.getPrototypeOf,d=l.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var f=d(a,b);if(void 0!==f)return f;a=c(a)}}function za(a,b,c){a=ya(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function Aa(a,b,c,d){a=ya(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new l.TypeError("super has no setter '"+c+"'.");}
var xa=null!==ea?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return ta(a);default:if(null===a)return 0;var b=ea.get(a);void 0===b&&(da=b=da+1|0,ea.set(a,b));return b}}:function(a){if(a&&a.a){var b=a.$idHashCode$0;if(void 0!==b)return b;if(l.Object.isSealed(a))return 42;da=b=da+1|0;return a.$idHashCode$0=b}return null===a?0:ta(a)};this.__ScalaJSExportsNamespace=aa;
function u(){this.ra=this.vb=void 0;this.S=this.W=this.r=null;this.U=0;this.rb=null;this.ja="";this.n=this.ha=this.ia=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function v(a,b,c){var d=new u;d.r={};d.W=null;d.rb=a;d.ja=b;d.n=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function w(a,b,c,d,f,h,k){var m=new u,r=fa(a);h=h||function(a){return!!(a&&a.a&&a.a.r[r])};k=k||function(a,b){return!!(a&&a.a&&a.a.U===b&&a.a.S.r[r])};m.ra=f;m.r=c;m.ja="L"+b+";";m.n=k;m.name=b;m.isInterface=!1;m.isRawJSType=!!d;m.isInstance=h;return m}
function Ca(a){function b(a){if("number"===typeof a){this.A=Array(a);for(var b=0;b<a;b++)this.A[b]=f}else this.A=a}var c=new u,d=a.rb,f="longZero"==d?x().ga:d;b.prototype=new y;b.prototype.constructor=b;b.prototype.a=c;var d="["+a.ja,h=a.S||a,k=a.U+1;c.vb=b;c.ra=Da;c.r={c:1,Z:1,e:1};c.W=a;c.S=h;c.U=k;c.rb=null;c.ja=d;c.ia=void 0;c.ha=void 0;c.n=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return h.n(a,k)};return c}
function q(a){if(!a.ia){var b=new z;b.ma=a;a.ia=b}return a.ia}function Ea(a){a.ha||(a.ha=Ca(a));return a.ha}u.prototype.getFakeInstance=function(){return this===ja?"some string":this===pa?!1:this===ka||this===la||this===ma||this===na||this===oa?0:this===sa?x().ga:this===qa?void 0:{a:this}};u.prototype.getSuperclass=function(){return this.ra?q(this.ra):null};u.prototype.getComponentType=function(){return this.W?q(this.W):null};
u.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=Ea(b);return ga(b,a,0)};var Fa=v(!1,"Z","boolean"),Ga=v(0,"C","char"),Ha=v(0,"B","byte"),Ia=v(0,"S","short"),Ja=v(0,"I","int"),Ka=v("longZero","J","long"),La=v(0,"F","float"),Ma=v(0,"D","double");Fa.n=p(Fa);Ga.n=p(Ga);Ha.n=p(Ha);Ia.n=p(Ia);Ja.n=p(Ja);Ka.n=p(Ka);La.n=p(La);Ma.n=p(Ma);function A(){}function y(){}y.prototype=A.prototype;A.prototype.b=function(){return this};A.prototype.h=function(){var a=Na(ia(this)),b=(+(this.j()>>>0)).toString(16);return a+"@"+b};A.prototype.j=function(){return xa(this)};A.prototype.toString=function(){return this.h()};var Da=w({c:0},"java.lang.Object",{c:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.a){var c=a.U||0;return!(c<b)&&(c>b||!a.S.isPrimitive)}return!1});A.prototype.a=Da;
function Oa(a){var b=a.V().N(),c=(new B).u(0);a.t(C(function(a,b,c){return function(a){b.Q(Qa(a,c.d));c.d=1+c.d|0}}(a,b,c)));return b.O()}function Ra(a,b,c,d,f){var h=Sa();Ta(b.q,c);a.t(C(function(a,b,c,d){return function(a){if(b.d)Ua(c,a),b.d=!1;else return Ta(c.q,d),Ua(c,a)}}(a,h,b,d)));Ta(b.q,f);return b}function Va(a,b,c){return a.tb((new D).b(),b,c,")").q.s}function Wa(a,b){var c;for(c=0;;)if(c<b&&a.p!==a)a=a.p,c=1+c|0;else break;c=a;if(!c.o())return c.X;throw(new E).k(""+b);}
function Xa(a,b){if(b>=a.z)throw(new E).k(""+b);return a.D.A[b]}function F(){}F.prototype=new y;F.prototype.constructor=F;F.prototype.b=function(){return this};
function Ya(a){var b=a.getContext("2d");a.width=a.parentElement.clientWidth|0;a.height=400;b.font="50px sans-serif";b.textAlign="center";b.textBaseline="middle";var c=Za((a.height|0)/2),d=Za(0),f=(new B).u(0),h=(new B).u(-50),k=$a().N().O();ab().setInterval(function(a,b,c,d,f,h,k,ac,Ba){return function(){bb();b.clearRect(0,0,a.width|0,a.height|0);0<k.d?(f.d=(a.height|0)/2|0,h.d=0,ac.d=-50,Ba.f=(new G).b(),Ba.l=Ba.f,Ba.g=0,k.d=-1+k.d|0,b.fillStyle="darkred",b.fillText("Game Over",(a.width|0)/2|0,(a.height|
0)/2|0)):cb(a,b,c,d,f,h,k,ac,Ba)}}(a,b,200,.1,c,d,f,h,k),20);a.onclick=function(a){return function(){a.d=-3.5+a.d}}(d)}function db(a,b){return(new eb).B(b.height|0,a)}
function cb(a,b,c,d,f,h,k,m,r){m.d=2+m.d|0;if(0<=m.d&&0===(m.d%c|0))for(var Pa=[db(20+fb(gb().w,31)|0,a)],L=0,Pc=Pa.length|0;L<Pc;)hb(r,Pa[L]),L=1+L|0;7<r.g&&(ib(r),m.d=m.d-c|0);f.d+=h.d;h.d+=d;b.fillStyle="darkblue";$a();jb(Oa(r),C(function(a){return null!==a})).t(C(function(a,b,c,d,f,h){return function(k){if(null!==k){var m=k.ea;k=(n(k.fa|0,c)-h.d|0)+(a.width|0)|0;b.fillRect(k,0,5,kb(m)-m.C|0);b.fillRect(k,kb(m)+m.C|0,5,((a.height|0)-kb(m)|0)-m.C|0);k=k-((a.width|0)/2|0)|0;5>(0>k?-k|0:k)?(k=kb(m)-
d.d,m=+l.Math.abs(k)>m.C):m=!1;m&&(f.d=50)}else throw(new H).jb(k);}}(a,b,c,f,k,m)));b.fillStyle="darkgreen";b.fillRect(-5+((a.width|0)/2|0)|0,-5+f.d,10,10);if(0>f.d||f.d>(a.height|0))k.d=50}F.prototype.main=function(a){Ya(a)};F.prototype.a=w({Sb:0},"example.ScalaJSExample$",{Sb:1,c:1});var lb=void 0;function bb(){lb||(lb=(new F).b());return lb}aa.example=aa.example||{};aa.example.ScalaJSExample=bb;function mb(){this.Pb=null;this.x=0}mb.prototype=new y;mb.prototype.constructor=mb;mb.prototype.b=function(){return this};
function ab(){var a;nb||(nb=(new mb).b());a=nb;0===(134217728&a.x)&&0===(134217728&a.x)&&(a.Pb=l,a.x|=134217728);return a.Pb}mb.prototype.a=w({Tb:0},"org.scalajs.dom.package$",{Tb:1,c:1});var nb=void 0;function z(){this.ma=null}z.prototype=new y;z.prototype.constructor=z;function Na(a){return a.ma.name}z.prototype.h=function(){return(this.ma.isInterface?"interface ":this.ma.isPrimitive?"":"class ")+Na(this)};z.prototype.a=w({cc:0},"java.lang.Class",{cc:1,c:1});function I(){}I.prototype=new y;
I.prototype.constructor=I;function ob(){}ob.prototype=I.prototype;I.prototype.lb=function(a,b){b=n(-862048943,b);b=n(461845907,b<<15|b>>>17|0);return a^b};I.prototype.M=function(a,b){a=this.lb(a,b);return-430675100+n(5,a<<13|a>>>19|0)|0};function pb(a){var b=qb(),c=a.sa();if(0===c)return a=a.ua(),ua(t(),a);for(var d=-889275714,f=0;f<c;)d=b.M(d,rb(sb(),a.ta(f))),f=1+f|0;return b.Y(d,c)}I.prototype.Y=function(a,b){a^=b;a=n(-2048144789,a^(a>>>16|0));a=n(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)};
function tb(a,b,c){var d=(new B).u(0);c=(new B).u(c);b.t(C(function(a,b,c){return function(d){c.d=a.M(c.d,rb(sb(),d));b.d=1+b.d|0}}(a,d,c)));return a.Y(c.d,d.d)}function ub(){}ub.prototype=new y;ub.prototype.constructor=ub;function vb(){}vb.prototype=ub.prototype;function wb(){this.K=!1;this.zb=this.na=this.T=null;this.gb=!1;this.Db=this.Ab=0}wb.prototype=new y;wb.prototype.constructor=wb;
wb.prototype.b=function(){xb=this;this.T=(this.K=!!(l.ArrayBuffer&&l.Int32Array&&l.Float32Array&&l.Float64Array))?new l.ArrayBuffer(8):null;this.na=this.K?new l.Int32Array(this.T,0,2):null;this.K&&new l.Float32Array(this.T,0,2);this.zb=this.K?new l.Float64Array(this.T,0,1):null;if(this.K)this.na[0]=16909060,a=1===((new l.Int8Array(this.T,0,8))[0]|0);else var a=!0;this.Ab=(this.gb=a)?0:1;this.Db=this.gb?1:0;return this};
function va(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.K)a.zb[0]=b,a=(new J).B(a.na[a.Db]|0,a.na[a.Ab]|0);else{if(b!==b)a=!1,b=2047,c=+l.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+l.Math.pow(2,-1022)){b=+l.Math.pow(2,52);var c=+l.Math.log(d)/.6931471805599453,c=+l.Math.floor(c)|0,c=1023>c?c:1023,f=d/+l.Math.pow(2,c)*b,d=+l.Math.floor(f),f=f-d,d=.5>f?d:.5<f?1+d:0!==d%2?1+d:d;2<=d/b&&(c=1+c|0,d=
1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+l.Math.pow(2,-1074),c=+l.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=(new J).B(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.I^a.F}wb.prototype.a=w({Kc:0},"scala.scalajs.runtime.Bits$",{Kc:1,c:1});var xb=void 0;function wa(){xb||(xb=(new wb).b());return xb}function yb(){this.x=!1}yb.prototype=new y;yb.prototype.constructor=yb;yb.prototype.b=function(){return this};
function zb(a){if(0===(-65536&a))return l.String.fromCharCode(a);if(0>a||1114111<a)throw(new K).b();a=-65536+a|0;return l.String.fromCharCode(55296|a>>10,56320|1023&a)}function ua(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+n(65535&(b.charCodeAt(d)|0),c)|0,c=n(31,c),d=-1+d|0;return a}yb.prototype.a=w({Mc:0},"scala.scalajs.runtime.RuntimeString$",{Mc:1,c:1});var Ab=void 0;function t(){Ab||(Ab=(new yb).b());return Ab}function Bb(){}Bb.prototype=new y;Bb.prototype.constructor=Bb;
Bb.prototype.b=function(){return this};function Cb(a,b){return b&&b.a&&b.a.r.qb?b.L:b}function Db(a,b){return b&&b.a&&b.a.r.$?b:(new Eb).jb(b)}Bb.prototype.a=w({Nc:0},"scala.scalajs.runtime.package$",{Nc:1,c:1});var Fb=void 0;function Gb(){Fb||(Fb=(new Bb).b());return Fb}function Hb(){}Hb.prototype=new y;Hb.prototype.constructor=Hb;Hb.prototype.b=function(){return this};
function rb(a,b){if(null===b)return 0;if(b&&b.a&&b.a.r.H||"number"===typeof b){if("number"===typeof b){a=+b;Ib();b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=x();var c;if(-9223372036854775808>a)b.Oa=-2147483648,c=0;else if(0x7fffffffffffffff<=a)b.Oa=2147483647,c=-1;else{c=a|0;var d=a/4294967296|0;b.Oa=0>a&&0!==c?-1+d|0:d}b=b.Oa;x();a=(0>b?-(4294967296*+((0!==c?~b:-b|0)>>>0)+ +((-c|0)>>>0)):4294967296*b+ +(c>>>0))===a?c^b:va(wa(),a)}return a}if(ra(b))return b=null===
b?x().ga:b,a=b.I,b=b.F,Ib(),b=(new J).B(a,b),a=b.I,b=b.F,b===a>>31?a:a^b}return ta(b)}Hb.prototype.a=w({Sc:0},"scala.runtime.ScalaRunTime$",{Sc:1,c:1});var Jb=void 0;function sb(){Jb||(Jb=(new Hb).b());return Jb}function Kb(){}Kb.prototype=new y;Kb.prototype.constructor=Kb;e=Kb.prototype;e.b=function(){return this};e.lb=function(a,b){b=n(-862048943,b);b=n(461845907,b<<15|b>>>17|0);return a^b};e.M=function(a,b){a=this.lb(a,b);return-430675100+n(5,a<<13|a>>>19|0)|0};
e.Y=function(a,b){a^=b;a=n(-2048144789,a^(a>>>16|0));a=n(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)};e.a=w({Uc:0},"scala.runtime.Statics$",{Uc:1,c:1});var Lb=void 0;function Ib(){Lb||(Lb=(new Kb).b());return Lb}function Mb(){}Mb.prototype=new y;Mb.prototype.constructor=Mb;function Nb(){}Nb.prototype=Mb.prototype;function M(){this.y=null}M.prototype=new y;M.prototype.constructor=M;function Ob(){}Ob.prototype=M.prototype;
M.prototype.yb=function(){if(void 0===l.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(a=Db(Gb(),b),null!==a)if(a&&a.a&&a.a.r.qb)a=a.L;else throw Cb(Gb(),a);else throw b;}this.stackdata=a}else l.Error.captureStackTrace(this),this.stackdata=this;return this};M.prototype.ib=function(){return this.y};M.prototype.h=function(){var a=Na(ia(this)),b=this.ib();return null===b?a:a+": "+b};M.prototype.G=function(a){this.y=a;this.yb();return this};function N(){this.ob=this.nb=0}N.prototype=new y;
N.prototype.constructor=N;N.prototype.b=function(){N.prototype.Xb.call(this,Pb());return this};N.prototype.Xb=function(a){var b=-554899859^a.I;this.nb=b>>>24|0|(65535&(5^a.F))<<8;this.ob=16777215&b;return this};function fb(a,b){if(0>=b)throw(new K).k("n must be positive");if((b&(-b|0))===b)a=Qb(a)>>ca(b);else a:for(;;){var c=Qb(a),d=c%b|0;if(!(0>((c-d|0)+(-1+b|0)|0))){a=d;break a}}return a}
function Qb(a){var b=a.ob,c=11+15525485*b,b=16777215&((c/16777216|0)+(16777215&(1502*b+15525485*a.nb|0))|0),c=16777215&(c|0);a.nb=b;a.ob=c;return(b<<8|c>>16)>>>1|0}N.prototype.a=w({mc:0},"java.util.Random",{mc:1,c:1,e:1});function Rb(){this.pb=0}Rb.prototype=new ob;Rb.prototype.constructor=Rb;Rb.prototype.b=function(){Sb=this;this.pb=ua(t(),"Seq");ua(t(),"Map");ua(t(),"Set");return this};
function Tb(a){var b=qb();if(a&&a.a&&a.a.r.jd){for(var c=0,d=b.pb,f=a;!f.o();)a=Ub(f),f=f.sd(),d=b.M(d,rb(sb(),a)),c=1+c|0;b=b.Y(d,c)}else b=tb(b,a,b.pb);return b}Rb.prototype.a=w({qc:0},"scala.util.hashing.MurmurHash3$",{qc:1,ad:1,c:1});var Sb=void 0;function qb(){Sb||(Sb=(new Rb).b());return Sb}function Vb(){this.P=this.Fb=null}Vb.prototype=new y;Vb.prototype.constructor=Vb;Vb.prototype.t=function(a){this.P.t(C(function(a,c){return function(d){return a.Fb.m(d)?c.m(d):void 0}}(this,a)))};
Vb.prototype.a=w({vc:0},"scala.collection.TraversableLike$WithFilter",{vc:1,c:1,da:1});function O(){}O.prototype=new vb;O.prototype.constructor=O;function Wb(){}Wb.prototype=O.prototype;O.prototype.b=function(){(new Xb).kb(this);return this};function Yb(){this.P=null}Yb.prototype=new y;Yb.prototype.constructor=Yb;function Zb(){}Zb.prototype=Yb.prototype;Yb.prototype.kb=function(a){if(null===a)throw Cb(Gb(),null);this.P=a;return this};function $b(){}$b.prototype=new y;$b.prototype.constructor=$b;
function bc(){}bc.prototype=$b.prototype;$b.prototype.h=function(){return"\x3cfunction1\x3e"};function cc(){this.d=!1}cc.prototype=new y;cc.prototype.constructor=cc;cc.prototype.h=function(){return""+this.d};function Sa(){var a=new cc;a.d=!0;return a}cc.prototype.a=w({Oc:0},"scala.runtime.BooleanRef",{Oc:1,c:1,e:1});var qa=w({Pc:0},"scala.runtime.BoxedUnit",{Pc:1,c:1,e:1},void 0,void 0,function(a){return void 0===a});function dc(){this.d=0}dc.prototype=new y;dc.prototype.constructor=dc;
function Za(a){var b=new dc;b.d=a;return b}dc.prototype.h=function(){return""+this.d};dc.prototype.a=w({Qc:0},"scala.runtime.DoubleRef",{Qc:1,c:1,e:1});function B(){this.d=0}B.prototype=new y;B.prototype.constructor=B;B.prototype.h=function(){return""+this.d};B.prototype.u=function(a){this.d=a;return this};B.prototype.a=w({Rc:0},"scala.runtime.IntRef",{Rc:1,c:1,e:1});var pa=w({$b:0},"java.lang.Boolean",{$b:1,c:1,e:1,v:1},void 0,void 0,function(a){return"boolean"===typeof a});
function P(){this.fb=0}P.prototype=new y;P.prototype.constructor=P;P.prototype.h=function(){return l.String.fromCharCode(this.fb)};function ec(a){var b=new P;b.fb=a;return b}P.prototype.j=function(){return this.fb};P.prototype.a=w({bc:0},"java.lang.Character",{bc:1,c:1,e:1,v:1});function fc(){this.y=null}fc.prototype=new Ob;fc.prototype.constructor=fc;function gc(){}gc.prototype=fc.prototype;function hc(){}hc.prototype=new y;hc.prototype.constructor=hc;hc.prototype.b=function(){return this};
function Pb(){ic||(ic=(new hc).b());var a=jc(),b=jc();return(new J).B(b,a)}function jc(){var a=4294967296*+l.Math.random(),a=-2147483648+ +l.Math.floor(a);return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}hc.prototype.a=w({nc:0},"java.util.Random$",{nc:1,c:1,i:1,e:1});var ic=void 0;function kc(){this.w=null}kc.prototype=new y;kc.prototype.constructor=kc;function lc(){}lc.prototype=kc.prototype;kc.prototype.Zb=function(a){this.w=a;return this};function mc(){}mc.prototype=new Wb;
mc.prototype.constructor=mc;function nc(){}nc.prototype=mc.prototype;function Xb(){this.P=null}Xb.prototype=new Zb;Xb.prototype.constructor=Xb;Xb.prototype.kb=function(a){if(null===a)throw Cb(Gb(),null);Yb.prototype.kb.call(this,a);return this};Xb.prototype.a=w({wc:0},"scala.collection.generic.GenTraversableFactory$$anon$1",{wc:1,gd:1,c:1,fd:1});function oc(){this.xb=null}oc.prototype=new bc;oc.prototype.constructor=oc;oc.prototype.m=function(a){return(0,this.xb)(a)};
function C(a){var b=new oc;b.xb=a;return b}oc.prototype.a=w({Jc:0},"scala.scalajs.runtime.AnonFunction1",{Jc:1,rd:1,c:1,R:1});function pc(){this.Oa=0;this.ga=null}pc.prototype=new y;pc.prototype.constructor=pc;pc.prototype.b=function(){qc=this;this.ga=(new J).B(0,0);return this};
function rc(a,b){if(0===(-2097152&b))return""+(4294967296*b+ +(a>>>0));var c=(32+ca(1E9)|0)-(0!==b?ca(b):32+ca(a)|0)|0,d=c,f=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,h=a,k=b;for(a=b=0;0<=c&&0!==(-2097152&k);){var m=h,r=k,Pa=f,L=d;if(r===L?(-2147483648^m)>=(-2147483648^Pa):(-2147483648^r)>=(-2147483648^L))m=k,r=d,k=h-f|0,m=(-2147483648^k)>(-2147483648^h)?-1+(m-r|0)|0:m-r|0,h=k,k=m,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;m=d>>>1|0;f=f>>>1|0|d<<31;d=m}c=k;if(0===c?-1147483648<=(-2147483648^
h):-2147483648<=(-2147483648^c))c=4294967296*k+ +(h>>>0),h=c/1E9,f=h/4294967296|0,d=b,b=h=d+(h|0)|0,a=(-2147483648^h)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,c%=1E9,h=c|0,k=c/4294967296|0;b=[b,a,h,k];a=""+(b["2"]|0);return""+(4294967296*(b["1"]|0)+ +((b["0"]|0)>>>0))+"000000000".substring(a.length|0)+a}pc.prototype.a=w({Lc:0},"scala.scalajs.runtime.RuntimeLong$",{Lc:1,c:1,i:1,e:1});var qc=void 0;function x(){qc||(qc=(new pc).b());return qc}
var ja=w({Ub:0},"java.lang.String",{Ub:1,c:1,e:1,Cb:1,v:1},void 0,void 0,function(a){return"string"===typeof a}),ka=w({ac:0},"java.lang.Byte",{ac:1,H:1,c:1,e:1,v:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),oa=w({dc:0},"java.lang.Double",{dc:1,H:1,c:1,e:1,v:1},void 0,void 0,function(a){return"number"===typeof a}),na=w({ec:0},"java.lang.Float",{ec:1,H:1,c:1,e:1,v:1},void 0,void 0,function(a){return"number"===typeof a}),ma=w({hc:0},"java.lang.Integer",{hc:1,H:1,c:1,e:1,v:1},void 0,
void 0,function(a){return(a|0)===a&&1/a!==1/-0}),sa=w({ic:0},"java.lang.Long",{ic:1,H:1,c:1,e:1,v:1},void 0,void 0,function(a){return ra(a)});function sc(){this.y=null}sc.prototype=new gc;sc.prototype.constructor=sc;function tc(){}tc.prototype=sc.prototype;var la=w({jc:0},"java.lang.Short",{jc:1,H:1,c:1,e:1,v:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function Q(){this.s=null}Q.prototype=new y;Q.prototype.constructor=Q;
function Ta(a,b){a.s=""+a.s+(null===b?"null":b);return a}Q.prototype.h=function(){return this.s};Q.prototype.u=function(){Q.prototype.k.call(this,"");return this};Q.prototype.k=function(a){this.s=a;return this};Q.prototype.a=w({kc:0},"java.lang.StringBuilder",{kc:1,c:1,Cb:1,Wc:1,e:1});function uc(){this.w=null}uc.prototype=new lc;uc.prototype.constructor=uc;uc.prototype.b=function(){kc.prototype.Zb.call(this,(new N).b());return this};
uc.prototype.a=w({pc:0},"scala.util.Random$",{pc:1,$c:1,c:1,i:1,e:1});var vc=void 0;function gb(){vc||(vc=(new uc).b());return vc}function R(){}R.prototype=new y;R.prototype.constructor=R;function wc(){}wc.prototype=R.prototype;R.prototype.o=function(){return!(this.E<this.la)};R.prototype.h=function(){return(this.E<this.la?"non-empty":"empty")+" iterator"};R.prototype.t=function(a){for(;this.E<this.la;)a.m(xc(this))};R.prototype.tb=function(a,b,c,d){return Ra(this,a,b,c,d)};
function J(){this.F=this.I=0}J.prototype=new Nb;J.prototype.constructor=J;e=J.prototype;e.h=function(){x();var a=this.I,b=this.F;return b===a>>31?""+a:0>b?"-"+rc(-a|0,0!==a?~b:-b|0):rc(a,b)};e.B=function(a,b){this.I=a;this.F=b;return this};e.u=function(a){J.prototype.B.call(this,a,a>>31);return this};e.j=function(){return this.I^this.F};function ra(a){return!!(a&&a.a&&a.a.r.Lb)}e.a=w({Lb:0},"scala.scalajs.runtime.RuntimeLong",{Lb:1,H:1,c:1,e:1,v:1});
function eb(){this.sb=this.C=this.ka=0;this.x=!1}eb.prototype=new y;eb.prototype.constructor=eb;e=eb.prototype;e.ua=function(){return"Obstacle"};e.sa=function(){return 2};e.ta=function(a){switch(a){case 0:return this.ka;case 1:return this.C;default:throw(new E).k(""+a);}};e.h=function(){sb();var a=this.mb();return Va(a,this.ua()+"(",",")};e.B=function(a,b){this.ka=a;this.C=b;return this};function kb(a){a.x||a.x||(a.sb=fb(gb().w,a.ka-(a.C<<1)|0),a.x=!0);return a.sb}
e.j=function(){var a=-889275714,a=Ib().M(a,this.ka),a=Ib().M(a,this.C);return Ib().Y(a,2)};e.mb=function(){return yc(this)};e.a=w({Rb:0},"example.Obstacle",{Rb:1,c:1,Gb:1,J:1,i:1,e:1});function K(){this.y=null}K.prototype=new tc;K.prototype.constructor=K;K.prototype.b=function(){M.prototype.G.call(this,null);return this};K.prototype.k=function(a){M.prototype.G.call(this,a);return this};K.prototype.a=w({fc:0},"java.lang.IllegalArgumentException",{fc:1,pa:1,oa:1,$:1,c:1,e:1});
function E(){this.y=null}E.prototype=new tc;E.prototype.constructor=E;E.prototype.k=function(a){M.prototype.G.call(this,a);return this};E.prototype.a=w({gc:0},"java.lang.IndexOutOfBoundsException",{gc:1,pa:1,oa:1,$:1,c:1,e:1});function S(){this.y=null}S.prototype=new tc;S.prototype.constructor=S;S.prototype.b=function(){M.prototype.G.call(this,null);return this};S.prototype.k=function(a){M.prototype.G.call(this,a);return this};
S.prototype.a=w({lc:0},"java.util.NoSuchElementException",{lc:1,pa:1,oa:1,$:1,c:1,e:1});function H(){this.Eb=this.aa=this.y=null;this.hb=!1}H.prototype=new tc;H.prototype.constructor=H;H.prototype.ib=function(){if(!this.hb&&!this.hb){var a;if(null===this.aa)a="null";else try{a=ha(this.aa)+" ("+("of class "+Na(ia(this.aa)))+")"}catch(b){if(null!==Db(Gb(),b))a="an instance of class "+Na(ia(this.aa));else throw b;}this.Eb=a;this.hb=!0}return this.Eb};
H.prototype.jb=function(a){this.aa=a;M.prototype.G.call(this,null);return this};H.prototype.a=w({oc:0},"scala.MatchError",{oc:1,pa:1,oa:1,$:1,c:1,e:1});function zc(){this.wb=this.w=null}zc.prototype=new y;zc.prototype.constructor=zc;function Ac(a,b,c){a.wb=c;a.w=b;return a}e=zc.prototype;e.h=function(){return""+this.w};e.O=function(){return this.wb.m(this.w.O())};e.Q=function(a){this.w.Q(a);return this};e.j=function(){return this.w.j()};
e.a=w({zc:0},"scala.collection.mutable.Builder$$anon$1",{zc:1,c:1,$a:1,Va:1,Pa:1,Yc:1});function Bc(){this.la=this.E=0;this.Qb=null}Bc.prototype=new wc;Bc.prototype.constructor=Bc;function xc(a){var b=a.Qb.ta(a.E);a.E=1+a.E|0;return b}function yc(a){var b=new Bc;b.Qb=a;b.E=0;b.la=a.sa();return b}Bc.prototype.a=w({Tc:0},"scala.runtime.ScalaRunTime$$anon$1",{Tc:1,bd:1,c:1,dd:1,ca:1,ba:1});function Cc(){this.fa=this.ea=null}Cc.prototype=new y;Cc.prototype.constructor=Cc;e=Cc.prototype;e.ua=function(){return"Tuple2"};
e.sa=function(){return 2};e.ta=function(a){a:switch(a){case 0:a=this.ea;break a;case 1:a=this.fa;break a;default:throw(new E).k(""+a);}return a};function Qa(a,b){var c=new Cc;c.ea=a;c.fa=b;return c}e.h=function(){return"("+this.ea+","+this.fa+")"};e.j=function(){return pb(this)};e.mb=function(){return yc(this)};e.a=w({Vb:0},"scala.Tuple2",{Vb:1,c:1,Xc:1,Gb:1,J:1,i:1,e:1});function Dc(){}Dc.prototype=new nc;Dc.prototype.constructor=Dc;function Ec(){}Ec.prototype=Dc.prototype;function T(){}
T.prototype=new Ec;T.prototype.constructor=T;T.prototype.b=function(){O.prototype.b.call(this);return this};T.prototype.N=function(){return(new U).b()};T.prototype.a=w({Bc:0},"scala.collection.mutable.IndexedSeq$",{Bc:1,Xa:1,Qa:1,Ra:1,Sa:1,c:1,Ya:1,Ta:1});var Fc=void 0;function Eb(){this.L=this.y=null}Eb.prototype=new tc;Eb.prototype.constructor=Eb;e=Eb.prototype;e.ua=function(){return"JavaScriptException"};e.sa=function(){return 1};e.yb=function(){this.stackdata=this.L;return this};
e.ta=function(a){switch(a){case 0:return this.L;default:throw(new E).k(""+a);}};e.ib=function(){return ha(this.L)};e.jb=function(a){this.L=a;M.prototype.G.call(this,null);return this};e.j=function(){return pb(this)};e.mb=function(){return yc(this)};e.a=w({qb:0},"scala.scalajs.js.JavaScriptException",{qb:1,pa:1,oa:1,$:1,c:1,e:1,Gb:1,J:1,i:1});function V(){}V.prototype=new Ec;V.prototype.constructor=V;V.prototype.b=function(){O.prototype.b.call(this);return this};V.prototype.N=function(){return(new U).b()};
V.prototype.a=w({yc:0},"scala.collection.mutable.ArrayBuffer$",{yc:1,Xa:1,Qa:1,Ra:1,Sa:1,c:1,Ya:1,Ta:1,i:1,e:1});var Gc=void 0;function W(){}W.prototype=new Ec;W.prototype.constructor=W;W.prototype.b=function(){O.prototype.b.call(this);return this};W.prototype.N=function(){var a=(new X).b();return Ac(new zc,a,C(function(){return function(a){return a.f}}(this)))};W.prototype.a=w({Ec:0},"scala.collection.mutable.LinkedList$",{Ec:1,Xa:1,Qa:1,Ra:1,Sa:1,c:1,Ya:1,Ta:1,i:1,e:1});var Hc=void 0;
function Y(){}Y.prototype=new Ec;Y.prototype.constructor=Y;Y.prototype.b=function(){O.prototype.b.call(this);return this};Y.prototype.N=function(){return(new X).b()};Y.prototype.a=w({Fc:0},"scala.collection.mutable.MutableList$",{Fc:1,Xa:1,Qa:1,Ra:1,Sa:1,c:1,Ya:1,Ta:1,i:1,e:1});var Ic=void 0;function Z(){}Z.prototype=new Ec;Z.prototype.constructor=Z;Z.prototype.b=function(){O.prototype.b.call(this);return this};
Z.prototype.N=function(){var a=(new X).b();return Ac(new zc,a,C(function(){return function(a){var c=a.f,d=a.l;a=a.g;var f=new Jc;X.prototype.b.call(f);f.f=c;f.l=d;f.g=a;return f}}(this)))};Z.prototype.a=w({Hc:0},"scala.collection.mutable.Queue$",{Hc:1,Xa:1,Qa:1,Ra:1,Sa:1,c:1,Ya:1,Ta:1,i:1,e:1});var Kc=void 0;function $a(){Kc||(Kc=(new Z).b());return Kc}function Lc(){}Lc.prototype=new y;Lc.prototype.constructor=Lc;function Mc(){}Mc.prototype=Lc.prototype;
function jb(a,b){var c=new Vb;c.Fb=b;if(null===a)throw Cb(Gb(),null);c.P=a;return c}Lc.prototype.tb=function(a,b,c,d){return Ra(this,a,b,c,d)};Lc.prototype.Mb=function(){var a=Na(ia(this)),b;t();b=a;var c=zb(46);b=b.lastIndexOf(c)|0;-1!==b&&(a=a.substring(1+b|0));t();b=a;c=zb(36);b=b.indexOf(c)|0;-1!==b&&(a=a.substring(0,b));return a};function Nc(){}Nc.prototype=new Mc;Nc.prototype.constructor=Nc;function Oc(){}Oc.prototype=Nc.prototype;function Qc(){}Qc.prototype=new Oc;
Qc.prototype.constructor=Qc;function Rc(){}Rc.prototype=Qc.prototype;Qc.prototype.h=function(){var a=this.Mb()+"(";return Va(this,a,", ")};function Sc(){}Sc.prototype=new Rc;Sc.prototype.constructor=Sc;function Tc(){}Tc.prototype=Sc.prototype;function G(){this.p=this.X=null}G.prototype=new Tc;G.prototype.constructor=G;e=G.prototype;e.b=function(){this.p=this;return this};e.m=function(a){return Wa(this,a|0)};e.o=function(){return this.p===this};e.V=function(){Hc||(Hc=(new W).b());return Hc};
e.t=function(a){for(var b=this;!b.o();)a.m(b.X),b=b.p};e.j=function(){return Tb(this)};e.a=w({Dc:0},"scala.collection.mutable.LinkedList",{Dc:1,Za:1,za:1,ya:1,Aa:1,c:1,Ma:1,Na:1,Wa:1,da:1,ca:1,ba:1,Ga:1,Ja:1,Fa:1,Ua:1,Ha:1,Ba:1,Ca:1,Ia:1,J:1,Ka:1,xa:1,R:1,Da:1,Ea:1,La:1,cb:1,bb:1,eb:1,wa:1,db:1,ab:1,va:1,Z:1,Jb:1,Hb:1,Ib:1,pd:1,i:1,e:1});function Uc(){}Uc.prototype=new Tc;Uc.prototype.constructor=Uc;function Vc(){}Vc.prototype=Uc.prototype;function X(){this.l=this.f=null;this.g=0}X.prototype=new Tc;
X.prototype.constructor=X;function Wc(){}Wc.prototype=X.prototype;function Ub(a){if(!a.o()){a=a.f;if(a.p===a)throw(new S).b();return a.X}throw(new S).b();}e=X.prototype;e.b=function(){this.l=this.f=(new G).b();this.g=0;return this};e.m=function(a){return Wa(this.f,a|0)};e.o=function(){return 0===this.g};e.V=function(){Ic||(Ic=(new Y).b());return Ic};e.t=function(a){for(var b=this;!b.o();)a.m(Ub(b)),b=b.Nb()};
function Xc(a,b){if(a.o())throw(new K).k("requirement failed: tail of empty list");var c=a.f;if(c.o())throw(new K).k("requirement failed: tail of empty list");b.f=c.p;b.g=-1+a.g|0;b.l=0===b.g?b.f:a.l}e.O=function(){return this};e.Nb=function(){return this.Ob()};e.Q=function(a){return hb(this,a)};e.j=function(){return Tb(this)};
function hb(a,b){if(0===a.g){var c=a.f,d=new G;G.prototype.b.call(d);null!==c&&(d.X=b,d.p=c);a.f=d;0===a.g&&(a.l=a.f)}else a.l.p=(new G).b(),a.l=a.l.p,a.l.X=b,a.l.p=(new G).b();a.g=1+a.g|0;return a}e.Ob=function(){var a=(new X).b();Xc(this,a);return a};
e.a=w({Kb:0},"scala.collection.mutable.MutableList",{Kb:1,Za:1,za:1,ya:1,Aa:1,c:1,Ma:1,Na:1,Wa:1,da:1,ca:1,ba:1,Ga:1,Ja:1,Fa:1,Ua:1,Ha:1,Ba:1,Ca:1,Ia:1,J:1,Ka:1,xa:1,R:1,Da:1,Ea:1,La:1,cb:1,bb:1,eb:1,wa:1,db:1,ab:1,va:1,Z:1,Jb:1,Hb:1,Ib:1,uc:1,$a:1,Va:1,Pa:1,i:1,e:1});function Jc(){X.call(this)}Jc.prototype=new Wc;Jc.prototype.constructor=Jc;e=Jc.prototype;e.b=function(){X.prototype.b.call(this);return this};
function ib(a){if(a.o())throw(new S).k("queue empty");a.f=a.f.p;a.g=-1+a.g|0;0===a.g&&(a.l=a.f)}e.V=function(){return $a()};e.Nb=function(){return Yc(this)};function Yc(a){var b=(new Jc).b();Xc(a,b);return b}e.Ob=function(){return Yc(this)};
e.a=w({Gc:0},"scala.collection.mutable.Queue",{Gc:1,Kb:1,Za:1,za:1,ya:1,Aa:1,c:1,Ma:1,Na:1,Wa:1,da:1,ca:1,ba:1,Ga:1,Ja:1,Fa:1,Ua:1,Ha:1,Ba:1,Ca:1,Ia:1,J:1,Ka:1,xa:1,R:1,Da:1,Ea:1,La:1,cb:1,bb:1,eb:1,wa:1,db:1,ab:1,va:1,Z:1,Jb:1,Hb:1,Ib:1,uc:1,$a:1,Va:1,Pa:1,i:1,e:1});function D(){this.q=null}D.prototype=new Tc;D.prototype.constructor=D;e=D.prototype;e.b=function(){D.prototype.Wb.call(this,16,"");return this};e.ub=function(a){a=65535&(this.q.s.charCodeAt(a)|0);return ec(a)};
e.m=function(a){a=65535&(this.q.s.charCodeAt(a|0)|0);return ec(a)};e.o=function(){return 0===this.qa()};e.h=function(){return this.q.s};e.V=function(){Fc||(Fc=(new T).b());return Fc};e.t=function(a){for(var b=0,c=this.qa();b<c;)a.m(this.ub(b)),b=1+b|0};e.O=function(){return this.q.s};e.Wb=function(a,b){D.prototype.Yb.call(this,Ta((new Q).u((b.length|0)+a|0),b));return this};e.qa=function(){return this.q.s.length|0};e.Yb=function(a){this.q=a;return this};
function Ua(a,b){var c=a.q;t();Ta(c,null===b?"null":ha(b));return a}e.Q=function(a){Ta(this.q,l.String.fromCharCode(null===a?0:a.fb));return this};e.j=function(){return Tb(this)};e.a=w({Ic:0},"scala.collection.mutable.StringBuilder",{Ic:1,Za:1,za:1,ya:1,Aa:1,c:1,Ma:1,Na:1,Wa:1,da:1,ca:1,ba:1,Ga:1,Ja:1,Fa:1,Ua:1,Ha:1,Ba:1,Ca:1,Ia:1,J:1,Ka:1,xa:1,R:1,Da:1,Ea:1,La:1,cb:1,bb:1,eb:1,wa:1,db:1,ab:1,va:1,Z:1,Cb:1,Ac:1,rc:1,sc:1,Cc:1,kd:1,tc:1,Zc:1,v:1,$a:1,Va:1,Pa:1,i:1,e:1});
function U(){this.Bb=0;this.D=null;this.z=0}U.prototype=new Vc;U.prototype.constructor=U;e=U.prototype;e.b=function(){U.prototype.u.call(this,16);return this};e.ub=function(a){return Xa(this,a)};e.m=function(a){return Xa(this,a|0)};e.o=function(){return 0===this.qa()};e.V=function(){Gc||(Gc=(new V).b());return Gc};e.t=function(a){for(var b=0,c=this.z;b<c;)a.m(this.D.A[b]),b=1+b|0};e.O=function(){return this};e.u=function(a){a=this.Bb=a;var b=Ea(Da);this.D=ga(b,[1<a?a:1],0);this.z=0;return this};
e.qa=function(){return this.z};
e.Q=function(a){var b=1+this.z|0,c=this.D.A.length,d=c>>31,f=b>>31;if(f===d?(-2147483648^b)>(-2147483648^c):f>d){f=c<<1;for(c=c>>>31|0|d<<1;;){var d=b>>31,h=f,k=c;if(d===k?(-2147483648^b)>(-2147483648^h):d>k)c=f>>>31|0|c<<1,f<<=1;else break}b=c;if(0===b?-1<(-2147483648^f):0<b)f=2147483647;b=f;f=Ea(Da);b=ga(f,[b],0);f=this.z;c=this.D.A;d=b.A;if(c!==d||0>0+f)for(h=0;h<f;h++)d[0+h]=c[0+h];else for(h=f-1;0<=h;h--)d[0+h]=c[0+h];this.D=b}this.D.A[this.z]=a;this.z=1+this.z|0;return this};e.j=function(){return Tb(this)};
e.Mb=function(){return"ArrayBuffer"};e.a=w({xc:0},"scala.collection.mutable.ArrayBuffer",{xc:1,ld:1,Za:1,za:1,ya:1,Aa:1,c:1,Ma:1,Na:1,Wa:1,da:1,ca:1,ba:1,Ga:1,Ja:1,Fa:1,Ua:1,Ha:1,Ba:1,Ca:1,Ia:1,J:1,Ka:1,xa:1,R:1,Da:1,Ea:1,La:1,cb:1,bb:1,eb:1,wa:1,db:1,ab:1,va:1,Z:1,md:1,nd:1,Va:1,Pa:1,hd:1,ed:1,id:1,od:1,Cc:1,sc:1,tc:1,$a:1,qd:1,Ac:1,rc:1,cd:1,i:1,e:1});
}).call(this);
//# sourceMappingURL=example-opt.js.map
